### ISSUE TITLE
clone --depth

### ISSUE THREAD

**Issue by coding-cgs** [eclipse-jgit/jgit#100]
Whether jgit supports the --depth parameter？
git clone --depth 10

**Comment by msohn** [comment]
JGit allows to set this option via [CloneCommand.setDepth(int)](https://github.com/eclipse-jgit/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/api/CloneCommand.java#L758) and the CLI clone command supports [`--depth`](https://github.com/eclipse-jgit/jgit/blob/master/org.eclipse.jgit.pgm/src/org/eclipse/jgit/pgm/Clone.java#L54).

**Comment by coding-cgs** [comment]
> Yes, JGit allows to set this option via [CloneCommand.setDepth(int)](https://github.com/eclipse-jgit/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/api/CloneCommand.java#L758) and the CLI clone command option [`--depth`](https://github.com/eclipse-jgit/jgit/blob/master/org.eclipse.jgit.pgm/src/org/eclipse/jgit/pgm/Clone.java#L54).

Thank you

This method is found in the higher version

**Comment by coding-cgs** [comment]
> Yes, JGit allows to set this option via [CloneCommand.setDepth(int)](https://github.com/eclipse-jgit/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/api/CloneCommand.java#L758) and the CLI clone command option [`--depth`](https://github.com/eclipse-jgit/jgit/blob/master/org.eclipse.jgit.pgm/src/org/eclipse/jgit/pgm/Clone.java#L54).

The version that supports CloneCommand.setDepth(int) does not support jdk8, the 5.13.3.202401111512-r version does not support this method, so can you compile a version with jdk8 that supports this method?

**Comment by msohn** [comment]
no, we don't add new features to old releases

**Comment by coding-cgs** [comment]
> no, we don't add new features to old releases



> no, we don't add new features to old releases

I mean can the latest version be compiled with jdk8?

**Comment by msohn** [comment]
no, since 7.0 we require Java 17
Java 17 is the second last LTS Java release
current Java LTS version is 21
latest Java release is 23
