### ISSUE TITLE
Optionally, ignore user and system config

### ISSUE THREAD

**Issue by reitzig** [eclipse-jgit/jgit#112]
### Description

I would like be able to suppress the default behaviour of JGit parsing `~/.gitconfig`.

### Motivation

We run integration tests of our application against a testcontainer. During those tests, we clone a repository from that server and perform commits.

JGit inadvertantly uses my `~/.gitconfig` which includes settings that 

- are irrelevant for this test, 
- create unnecessary brittleness (different devs have different Git configs), _and_ 
- are not all supported by JGit (e.g. commit signing with SSH keys), leading to false-red tests.

### Alternatives considered

In a very old discussion thread, mention was made of overwriting `$HOME` and similar variables. That seems like using a sledgehammer, and I'm not sure how to even _do_ this in a JUnit test context without untold numbers of side-effects.

In principle, I could at least avoid _red_ tests by tuning my local config so that the tests run through. Unfortunately, `includeIf` is not supported either #9. Even if, we'd still couple tests to host config -- meh.

### Additional context

I searched for and through the docs, but encountered a couple of 404s. I could not find any mention of how to configure JGit at all, which makes me suspicious. Did I miss something?

**Comment by msohn** [comment]
You can install a custom `SystemReader` to load global git config files from another file, or not load them.
JGit tests do that using its [`MockSystemReader`](https://github.com/eclipse-jgit/jgit/blob/master/org.eclipse.jgit.junit/src/org/eclipse/jgit/junit/MockSystemReader.java#L42).

If this mock doesn't match your needs you can implement your own, [`SystemReader.Delegate`](https://github.com/eclipse-jgit/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/util/SystemReader.java#L189) simplifies this, you only need to override the methods you want to change.

Install a SystemReader which loads config files from a temp directory:
```
    SystemReader oldSystemReader = SystemReader.getInstance();
    SystemReader.setInstance(
        new SystemReader.Delegate(oldSystemReader) {
          @Override
          public FileBasedConfig openJGitConfig(Config parent, FS fs) {
            return new FileBasedConfig(parent, new File(tempDir, "jgit.config"), FS.detect());
          }

          @Override
          public FileBasedConfig openUserConfig(Config parent, FS fs) {
            return new FileBasedConfig(parent, new File(tempDir, "user.config"), FS.detect());
          }

          @Override
          public FileBasedConfig openSystemConfig(Config parent, FS fs) {
            return new FileBasedConfig(parent, new File(tempDir, "system.config"), FS.detect());
          }
        });
```

**Comment by msohn** [comment]
If you want to skip some of these config files you can return a dummy FileBasedConfig:

```
return new FileBasedConfig(parent, null, fs) {
	@Override
	public void load() {}

	@Override
	public boolean isOutdated() {
		return false;
	}
};
```

**Comment by msohn** [comment]
JGit supports the [`GIT_CONFIG_NOSYSTEM` environment variable](https://git-scm.com/docs/git-config#Documentation/git-config.txt-GITCONFIGNOSYSTEM)

**Comment by reitzig** [comment]
Thank  you, that was helpful! 🙏

**Comment by Zacharia2** [comment]
#25449
