### ISSUE TITLE
Blame command returns null result for gradle module

### ISSUE THREAD

**Issue by unkali** [eclipse-jgit/jgit#119]
### Version

All versions after 5.5.1

### Operating System

MacOS

### Bug description

I have a gradle project with the following repository structure (Java version : 17)
```
my-api
    .github/
    .idea/
    gradle/
    .gitignore
    settings.gradle
    my-api
        build.gradle
        src
            main
                java
                    com.example
                        Application.java
```
The blame command works for files which are direct children of `my-api` except for any files under `my-api/my-api` module.
Please see the following code that I am using to check this behaviour
```
public class Jgit {

    static final String REPO = "/Users/kapil-mangtani/IdeaProjects/my-api/.git";
    static final String PATH1 = "settings.gradle";
    static final String PATH2 = ".github/workflows/build-deploy-dev.yml";
    static final String PATH3 = "my-api/src/main/java/com/example/Application.java";

    public static void main(String[] args) throws Exception {
        FileRepositoryBuilder builder = new FileRepositoryBuilder();
        Git git = new Git(builder.setGitDir(new File(REPO)).readEnvironment().findGitDir().build());

        BlameCommand blameCommand = git.blame().setFilePath(PATH1);
        BlameResult result = blameCommand.call();
        assert result != null;   // TRUE

        BlameCommand blameCommand1 = git.blame().setFilePath(PATH2);
        BlameResult result1 = blameCommand1.call();
        assert result1 != null;  // TRUE

        BlameCommand blameCommand2 = git.blame().setFilePath(PATH3);
        BlameResult result2 = blameCommand2.call();
        assert result2 != null;  // FALSE for versions above 5.5.1
}
```
In my build.gradle file, I have
`implementation 'org.eclipse.jgit:org.eclipse.jgit:<version>'`

Now when the `version` is 5.5.1 or below, `result2` is not null and contains the blame result, but any version after that eg. 5.13.3, or 6.2.0 or even the latest one 7.1.0 returns the result2 as null. I have verified the same behaviour using the standalone sh file as well for the same versions using the `blame -w` command

### Actual behavior

blame result is null as seen in the code snippet above

### Expected behavior

blame result to be non-null with author and commit information (as seen in versions 5.5.1 and prior)

### Other information

Public repo for reproducing this behaviour: https://github.com/kapman17/jgit-test/tree/failure

Additional information: I have found that using a [gradle plugin to manage Git hooks](https://github.com/jakemarsden/git-hooks-gradle-plugin) causes this issue. When I remove the plugin, the blame command works just fine.

_No response_

**Comment by tomaswolf** [comment]
Please provide a Github public repo with which one can reproduce this.

**Comment by unkali** [comment]
@tomaswolf Please check out this repo : https://github.com/kapman17/jgit-test/tree/failure

I have narrowed down the issue to a gradle plugin for managing git hooks in the repository. The plugin is `'com.github.jakemarsden.git-hooks' (link: https://github.com/jakemarsden/git-hooks-gradle-plugin). The main branch of the repo above does not have the plugin and the blame command works fine there (see [Jgit.java](https://github.com/kapman17/jgit-test/blob/failure/demo/src/main/java/com/example/demo/Jgit.java)) . However, if you switch to the `failure` branch, you can easily reproduce the above issue. 

On the failure branch, blame command returns null with version above 5.5.1

**Comment by tomaswolf** [comment]
This is a gradle configuration problem.

The `com.github.jakemarsden.git-hooks` plug-in as configured generates its hook at `jgit-test/demo/.git/hooks/pre-push`. Because there is a `.git` directory inside `demo` then, JGit treats `demo` as a nested git repository and does not traverse into that folder.

You need to configure that plug-in in `demo/build.gradle` to generate its hook file in the correct place like this 
```
gitHooks {
	hooks = ['pre-push': 'spotlessCheck']
	hooksDirectory = file('../.git/hooks')
}
```

Then everything works fine.

**Comment by unkali** [comment]
that makes sense, thanks @tomaswolf !
