### ISSUE TITLE
Security bug reporting instructions refer to Bugzilla

### ISSUE THREAD

**Issue by jrn** [eclipse-jgit/jgit#31]
### Bug description

https://github.com/eclipse-jgit/jgit/security/policy states:

> "The community is also encouraged to report vulnerabilities using the Eclipse Foundation's Bugzilla instance. Note that you will require an Eclipse Foundation account to create an issue report, but by doing so you will be able to participate directly in the resolution of the issue.
>
> Issue reports related to vulnerabilities must be marked as "committers-only", either automatically by clicking the provided link, by the reporter, or by a committer during the triage process. Note that issues marked "committers-only" are visible to all Eclipse committers. By default, a "committers-only" issue is also accessible to the reporter and individuals explicitly indicated in the "cc" list.

What is the github issues equivalent that we should be following?

### Actual behavior

Instructions refer to the previous (bugzilla) bug tracker.

### Expected behavior

Instructions refer to the current bug tracker.

**Comment by msohn** [comment]
Thanks for the heads up, looks like we missed this when migrating from Bugzilla.

According to [1] we can either via confidential issues (GitLab) or private security advisories (GitHub).
AFAIR for tracking past security issues we used confidential GitLab issues, they came in via the Eclipse security team.
This worked well for me. I have no experience using GitHub security advisories. Maybe you have ?
What's your preference ?

[1] https://www.eclipse.org/projects/handbook/#project-setup-for-vulnerability-reporting

**Comment by msohn** [comment]
@mrybczyn what's your recommendation from the Eclipse security team ?

**Comment by tomaswolf** [comment]
Can't we just remove our own SECURITY.md file in the repo and have the foundation's global one be used then by default?

**Comment by msohn** [comment]
AFAIR I was asked to add the SECURITY.md by EMO

**Comment by jrn** [comment]
> AFAIR for tracking past security issues we used confidential GitLab issues, they came in via the Eclipse security team [2].
This worked well for me hence I'd tend to stick to this path.

I agree, this is a good path.

> I have no experience using GitHub security advisories. Maybe you have ?

They're good for getting a CVE identifier and advertising it, but I didn't find them more useful than other tools for handling the flow of fixing an issue.

**Comment by msohn** [comment]
I pushed an update of SECURITY.md https://review.gerrithub.io/c/eclipse-jgit/jgit/+/1177352
using the text from https://www.eclipse.org/security/.

**Comment by msohn** [comment]
submitted update of SECURITY.md
