### ISSUE TITLE
Jetty 10 is at End of Community Support - upgrade to Jetty 12

### ISSUE THREAD

**Issue by joakime** [eclipse-jgit/jgit#41]
### Version

All

### Operating System

Linux/Unix

### Bug description

jgit is still using an End of Community Support version of Jetty.

See:

* https://github.com/jetty/jetty.project/issues/10485

### Actual behavior

Not possible to use the only supported version of Jetty at the moment.

### Expected behavior

Upgrade to Jetty 12.

Note: if you want to stick with the `javax.servlet` namespace, then use the `ee8` environment on Jetty 12.

**Comment by andrew-tram** [comment]
I was wondering if anybody had thoughts on this.

**Comment by joakime** [comment]
Note, you can use `javax.servlet` on Jetty 12 via the `ee8` environment.

**Comment by msohn** [comment]
depends on update to Java 17 #52

**Comment by msohn** [comment]
Update to 
- jetty 11.0.20 and jakarta.servlet 5.0: https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/189213
- jetty 12.0.8 and jakarta.servlet 6.0: https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1194291

**Comment by msohn** [comment]
JGit releases (existing and planned) are listed here https://projects.eclipse.org/projects/technology.jgit

The next release 6.10 is planned to be shipped with Eclipse IDE 2024-06 on June 12, 2024.
We plan to ship the update to Jetty 12 (see issue 41) with JGit 7.0 with Eclipse IDE 2024-06 on Sep 11, 2024.

**Comment by msohn** [comment]
servlet API was updated to jakarta.servlet 6.1.0 in https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1200138

closing since changes were merged and shipped with 7.0.0 on Sep 11
