### ISSUE TITLE
Gradle plugin Compatibility ?

### ISSUE THREAD

**Issue by Xinerfapre** [eclipse-jgit/jgit#51]
### Description

Hello,

Is it possible to make a plugin for Gradle ?

### Motivation

I would like to use JGit to manage my versions and my Git repository in the file "build.gradle.kts".

**Comment by tomaswolf** [comment]
We do not create or maintain build systems. Plug-ins for maven or gradle or other build systems are created and maintained by the people developing these build systems.

Check with the gradle community what already exists, and if you need something that doesn't exist yet, then see with the gradle community how to get or implement the functionality you need in the gradle ecosystem.
