### ISSUE TITLE
Keep target platform dependencies up-to-date

### ISSUE THREAD

**Issue by merks** [eclipse-jgit/jgit#55]
### Description

Orbit generates a report for JGit's target platform:

https://github.com/eclipse-orbit/orbit-simrel/blob/main/report/maven-osgi/jgit/REPORT.md

You can literally copy and paste this updated version:

https://github.com/eclipse-orbit/orbit-simrel/blob/main/report/maven-osgi/jgit/updated.target

to replace this version:

https://raw.githubusercontent.com/eclipse-jgit/jgit/master/org.eclipse.jgit.packaging/org.eclipse.jgit.target/jgit-4.32.target

The reports are generally regenerated 5+ times per week.

---

## Minor Updates
 - [commons-codec](https://repo1.maven.org/maven2/commons-codec/)
    - [commons-codec](https://repo1.maven.org/maven2/commons-codec/commons-codec/) **[1.16.0](https://repo1.maven.org/maven2/commons-codec/commons-codec/1.16.0)** < [1.17.0](https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.0/)
 - [commons-io](https://repo1.maven.org/maven2/commons-io/)
    - [commons-io](https://repo1.maven.org/maven2/commons-io/commons-io/) **[2.15.1](https://repo1.maven.org/maven2/commons-io/commons-io/2.15.1)** < [2.16.1](https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/)
 - [commons-logging](https://repo1.maven.org/maven2/commons-logging/)
    - [commons-logging](https://repo1.maven.org/maven2/commons-logging/commons-logging/) **[1.2](https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2)** < [1.3.2](https://repo1.maven.org/maven2/commons-logging/commons-logging/1.3.2/)
 - [org.eclipse.jetty](https://repo1.maven.org/maven2/org/eclipse/jetty/)
    - [jetty-http](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/) **[10.0.20](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/10.0.20)** < [10.0.21](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/10.0.21/)
    - [jetty-io](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/) **[10.0.20](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/10.0.20)** < [10.0.21](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/10.0.21/)
    - [jetty-security](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-security/) **[10.0.20](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-security/10.0.20)** < [10.0.21](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-security/10.0.21/)
    - [jetty-server](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/) **[10.0.20](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/10.0.20)** < [10.0.21](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/10.0.21/)
    - [jetty-servlet](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlet/) **[10.0.20](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlet/10.0.20)** < [10.0.21](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlet/10.0.21/)
    - [jetty-util](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/) **[10.0.20](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/10.0.20)** < [10.0.21](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/10.0.21/)
    - [jetty-util-ajax](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util-ajax/) **[10.0.20](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util-ajax/10.0.20)** < [10.0.21](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util-ajax/10.0.21/)

### Motivation

It's best to use the latest dependencies.

**Comment by msohn** [comment]
Pushed this series for review to fix this
https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1194979

**Comment by merks** [comment]
@msohn 

The same question as for EGit arises for JGit:

https://github.com/eclipse-egit/egit/issues/34#issuecomment-2120233046

I.e., is there are purpose to multiple versions of this artifact?

https://github.com/eclipse-jgit/jgit/blob/cac835835d2e7789f2a01c03da83b44185668269/org.eclipse.jgit.packaging/org.eclipse.jgit.target/maven/dependencies.tpd#L20-L29

**Comment by merks** [comment]
FYI, the report generator now generates an updated *.tpd:

https://github.com/eclipse-orbit/orbit-simrel/blob/main/report/maven-osgi/jgit/updated.tpd

**Comment by msohn** [comment]
updates were submitted
