### ISSUE TITLE
use jgit impl  "git show commitId --name-only"

### ISSUE THREAD

**Issue by lpf4254302** [eclipse-jgit/jgit#63]
### Description

use jgit impl  "git show commitId --name-only"

### Motivation

give a commitId then return commit files

**Comment by msohn** [comment]
The jgit command line application supports this command, see https://github.com/eclipse-jgit/jgit/blob/master/org.eclipse.jgit.pgm/src/org/eclipse/jgit/pgm/Show.java#L97
