### ISSUE TITLE
Submodules: use relative paths as worktree and gitdir instead of absolute ones

### ISSUE THREAD

**Issue by eder-s** [eclipse-jgit/jgit#78]
### Description

Support relative paths for:
- a submodule's worktree configuration entry 
- a submodule's gitdir link

### Motivation

Using relative paths allows copying the super project to a different locations w/o worrying about the submodules.
With absolute paths the submodules do still point to the "old" location after the superpoject is copied.

### Additional context

This issue was addressed previously at:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=463437

"cgit" also uses relative paths for worktree and gitdir.

**Comment by tomaswolf** [comment]
This is at 

https://github.com/eclipse-jgit/jgit/blob/299a7348eb318a0199226c1e633cc46c659d76d3/org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/file/FileRepository.java#L296-L304

Reading core.worktree and the .git file already resolves them.
